version: "3.9"

services:
  maria-db:
    image: mariadb
    container_name: go-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: go-test-komgrip
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - db-network
    volumes:
      - mariadb_data:/var/lib/mysql

  mongo:
    image: mongo
    container_name: go-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27030:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - db-network

volumes:
  mariadb_data:
  mongo_data:

networks:
  db-network:
