server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M"
  timeout: 30

mariadb:
  user: root
  password: 1234
  database: go-test-komgrip
  host: localhost
  port: 3307

mongodb:
  user: root
  password: 1234
  host: 0.0.0.0
  port: 27030
